name: test-push
on: push
jobs:
  test-check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry
      - name: install poetry
        run: make install
      - name: build gendiff
        run: make build
      - name: install tester
        run: poetry add --dev pytest
      - name: run tester
        run: make test