name: test-push
on: push
jobs:
  test-check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install pytest
        run: 
          python3 -m pip install --upgrade pip
          pip install pytest
      - name: run tester
        run: pytest tests